app:
  - changed-files:
      - any-glob-to-any-file: "app/**"

tests:
  - changed-files:
      - any-glob-to-any-file: "tests/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile"
          - "docker-compose.yml"
          - ".dockerignore"

helm:
  - changed-files:
      - any-glob-to-any-file: "charts/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"
          - "requirements*.txt"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "LICENSE"
