{{- if and .Values.rabbitmq.enabled .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-market-orders-fetch-worker
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}-market-orders-fetch-worker
  minReplicaCount: {{ .Values.eveBuild.marketOrders.fetchWorker.keda.minReplicas }}
  maxReplicaCount: {{ .Values.eveBuild.marketOrders.fetchWorker.keda.maxReplicas }}
  pollingInterval: {{ .Values.eveBuild.marketOrders.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.eveBuild.marketOrders.keda.cooldownPeriod }}
  triggers:
    - type: rabbitmq
      metadata:
        queueName: market_orders.scrape_jobs
        mode: QueueLength
        value: {{ .Values.eveBuild.marketOrders.fetchWorker.keda.queueLength | quote }}
        protocol: amqp
      authenticationRef:
        name: {{ .Release.Name }}-rabbitmq-conn
{{- end }}
