{{- if and .Values.redis.enabled .Values.redis.exporter.enabled .Values.redis.exporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-redis
    {{- with .Values.redis.exporter.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.redis.exporter.serviceMonitor.interval }}
{{- end }}
