apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
{{- with .Values.eveBuild.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
